# Generated by Django 5.2.8 on 2025-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("creator", "Creator"), ("editor", "Editor")],
                default="editor",
                max_length=10,
            ),
        ),
    ]
