# Generated by Django 5.2.8 on 2025-11-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="footage_link",
            field=models.URLField(blank=True),
        ),
    ]
