# Generated by Django 5.2.8 on 2025-11-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bounty_footage_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bounty",
            old_name="budget",
            new_name="budget_min",
        ),
        migrations.AddField(
            model_name="bounty",
            name="budget_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bounty",
            name="footage_link",
            field=models.URLField(),
        ),
    ]
