# Generated by Django 5.2.8 on 2026-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customuser_bio_customuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="bounty",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="bounties", to="core.tag"
            ),
        ),
    ]
